PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX a: <http://www.daml.org/2001/01/gedcom/gedcom#>

SELECT ?i ?n 
WHERE
 { ?i rdf:type a:Individual .
   ?i a:name ?n .
	FILTER ( regex ( str(?n), "Beatrix") )
 }

